Imports System.Net.Mail

Module UserMail

    'E-mail-related functions
    Function NewPasswordEmail(ByVal name As String, ByVal login As String, ByVal password As String) As String
        Dim body As String
        Dim link As String = "http://core-pso.speedware.com/Perdiems/"


        body = "Sent from mis@freschelegacy.com on behalf of the Per Diem application." + vbCrLf + vbCrLf + vbCrLf +
                           "Hello " + name + "," +
                           vbCrLf + vbCrLf +
                           "You are receiving this e-mail on behalf of  Fresche Legacy's " +
                           "Per Diem application. You have now been granted access to the application, " +
                           "and can access it at: " + link + vbCrLf + vbCrLf +
                           "This application exists alongside current expense systems to accommodate Fresche Legacy's " +
                           "Per Diem requirements. It interfaces with the expense system you use and enters your requests " +
                           "as an expense entry. Please use this application to enter your Per Diem requests. " +
                           "DO NOT select Per Diem Activity within V1 PSA." + vbCrLf + vbCrLf +
                           "You can login using the following credentials:" + vbCrLf + vbCrLf +
                           "Username: " + login + vbCrLf +
                           "Password: " + password + vbCrLf + vbCrLf +
                           "Please note that upon first login you will be asked to reset your " +
                           "Password, and set a personal security question, and answer, for " +
                           "Password reset services. For simplicity, We strongly recommend " +
                           "setting your new Password to the same one you use to login to " +
                           "the exepense system you use." + vbCrLf + vbCrLf +
                           "This system is designed to replicate the old Per Diem system and works " +
                           "similarly. If you had never used the previous system, or require additional " +
                           "information about how to submit a Per Diem, please refer to the user documentation " +
                           "guide at: http://core-pso.speedware.com/PerDiems/Docs/UserGuide.pdf" + vbCrLf +
                           "Or on the central repository at <\\nas1-mon-can\Group Shares\Central Repository\IT\V1 PSA>" + "\n\n" +
                           "Thank you, " + name + ", and have a nice day!" + vbCrLf + vbCrLf +
                           "This e-mail was auto-generated by the Per Diem application, and not " +
                           "monitored by any person(s). If you encounter any issues with the " +
                           "System, or have any " +
                           "questions, please submit a ticket to the IT helpdesk under the ""MIS"" category."

        Return body
    End Function

    Function SendEmail(ByVal sender As String, ByVal email As String, ByVal subject As String, ByVal body As String) As Boolean
        Dim status As Boolean

        Try
            Dim newMail As New MailMessage()
            newMail.To.Add(New MailAddress(email))
            newMail.From = New MailAddress(sender)
            newMail.Subject = subject
            newMail.Body = body

            Dim mailClient As New SmtpClient("smtp.gmail.com", 465)
            mailClient.EnableSsl = True

            mailClient.Credentials = New Net.NetworkCredential("SilCORECB@gmail.com", "64trinity92")

            mailClient.DeliveryMethod = SmtpDeliveryMethod.Network
            mailClient.Send(newMail)

            status = True
        Catch ex As Exception
            NewErrorMail(ex.ToString, "The initial login information e-mail was unable To be sent. Please contact HR And IT To verify the address: " + email + ".", "SendEMail Function")
            status = False
        End Try

        Return status
    End Function

    'E-mail-related subs
    Sub NewErrorMail(ByVal ex As String, ByVal cause As String, ByVal location As String)

        Dim body As String = "The following error has occurred when attempting to load a V1 resource into the Per Diem system:" + vbCrLf + vbCrLf +
                             "Location: " + location + vbCrLf + vbCrLf +
                             "Most likely cause: " + cause + vbCrLf + vbCrLf +
                             "Exception: " + ex

        Dim mailSent As Boolean = SendEmail("PerDiemLoadModule@FrescheLegacy.com", "Scribe@FrescheLegacy.com", "There has been an error when loading a resource into the Per Diem system.", body)
    End Sub

End Module
